//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScriptCenter.Package {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PackageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PackageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScriptCenter.Package.PackageResources", typeof(PackageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (
        ///	function checkDotNetVersion =
        ///	(
        ///		--Returns true if the .NET Framework 3.5 key could be opened.
        ///		local rKey;
        ///		local success = registry.openkey HKEY_LOCAL_MACHINE &quot;SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.5&quot; key:&amp;rKey accessright:#readonly;
        ///		if (success) do
        ///			registry.closeKey rKey;
        ///		
        ///		if (not success) do
        ///		(
        ///			success = registry.openkey HKEY_LOCAL_MACHINE &quot;SOFTWARE\Microsoft\NET Framework Setup\NDP\v4&quot; key:&amp;rKey accessright:#readonly;
        ///			if (success) do
        ///				registry.closeKey rKe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string install {
            get {
                return ResourceManager.GetString("install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name &quot;{id}&quot;
        ///version {version_major}.{version_minor}{version_rev}
        ///
        ///extract to &quot;$temp/{id}&quot;
        ///
        ///run &quot;installer/install.ms&quot;
        ///drop &quot;installer/install.ms&quot;.
        /// </summary>
        internal static string mzp {
            get {
                return ResourceManager.GetString("mzp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {name} installer
        ///
        ///This package was created using ScriptCenter.
        ///It should be started either through ScriptCenter plugin or as a standalone installer (by dropping it onto 
        ///a 3dsmax viewport, or using the menu MaxScript -&gt; Run Script)..
        /// </summary>
        internal static string README {
            get {
                return ResourceManager.GetString("README", resourceCulture);
            }
        }
    }
}
